"""`.mlpackage` and `.mlmodel` over Core ML, on the Neural Engine where there is one.

Docs: https://vedicreader.github.io/anya/apple.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_apple.ipynb.

# %% ../nbs/04_apple.ipynb #f37fe9c3
from __future__ import annotations
from pathlib import Path

import numpy as np
from fastcore.all import AttrDict, L

from .core import Model, Pred, infer_task, model_file, prep_from_spec, with_hub_defaults
from .vision import Prep, decode_classify, read_labels

# %% auto #0
__all__ = ['ct_spec', 'decode_class_dict', 'CoreMLModel']

# %% ../nbs/04_apple.ipynb #e00e878b
def _feat(f) -> AttrDict:
    'One input or output feature of a Core ML model as a plain row.'
    t = f.type.WhichOneof('Type')
    if t == 'imageType':
        return AttrDict(name=f.name, kind='image', shape=[1, int(f.type.imageType.height),
                                                          int(f.type.imageType.width), 3], dtype='uint8',
                        color=f.type.imageType.colorSpace)
    if t == 'multiArrayType':
        return AttrDict(name=f.name, kind='array', shape=[1] + [int(d) for d in f.type.multiArrayType.shape],
                        dtype='float32')
    return AttrDict(name=f.name, kind=t or 'unknown', shape=[], dtype='float32')

def ct_spec(mlmodel) -> AttrDict:
    'Input and output rows for a loaded `coremltools` model.'
    d = mlmodel.get_spec().description
    return AttrDict(inputs=L(d.input).map(_feat), outputs=L(d.output).map(_feat),
                    kind=mlmodel.get_spec().WhichOneof('Type'))

# %% ../nbs/04_apple.ipynb #c3e6ea21
def decode_class_dict(d:dict,           # a Core ML classifier's {label: probability}
                      topk:int=5
                     ) -> list:
    'Rank a Core ML classifier probability dictionary the way `decode_classify` ranks a tensor.'
    xs = sorted(d.items(), key=lambda t: -float(t[1]))[:max(1, topk)]
    return [dict(label=str(k), score=round(float(v), 6), index=i) for i, (k, v) in enumerate(xs)]

# %% ../nbs/04_apple.ipynb #8ae7b3fc
class CoreMLModel(Model):
    'A Core ML model as a `Model`. Image inputs go in as PIL images at the size the model fixes.'
    _runtime = 'coreml'

    def __init__(self,
                 model=None,               # a path to .mlpackage/.mlmodel, or a hub repo id
                 *,
                 runtime:str=None,
                 model_path=None,
                 file:str=None,
                 revision:str=None,
                 task:str=None,
                 labels=None,
                 norm=None,
                 size:tuple=None,
                 resize:str=None,
                 prep=None,
                 topk:int=5, conf:float=0.25, iou:float=0.45,
                 compute_units:str='ALL',  # 'ALL', 'CPU_ONLY', 'CPU_AND_GPU', 'CPU_AND_NE'
                 mlmodel=None,             # an already-loaded coremltools model
                 **kw):
        model = self._setup(model, task=task, labels=labels, topk=topk, conf=conf, iou=iou)
        self.model_path = str(model_file(model, model_path, file=file, revision=revision))
        self._sess = mlmodel or self._mk_model(compute_units, **kw)
        s = ct_spec(self._sess)
        self.inputs, self.outputs, self.kind = s.inputs, s.outputs, s.kind
        if len(self.inputs) > 1: raise ValueError(
            f'{Path(self.model_path).name} takes {len(self.inputs)} inputs; anya drives single-input models.')
        self.inp = self.inputs[0]
        labels, norm, size, resize = with_hub_defaults(self.model_path, self.labels, norm, size, resize)
        self.labels = read_labels(labels)
        self._task = task or ('classify' if self.kind == 'neuralNetworkClassifier'
                              else infer_task([o.shape for o in self.outputs], self.labels,
                                              [o.name for o in self.outputs]))
        # an image input is resized and handed over as pixels: Core ML owns the normalisation
        self._prep = prep or (Prep(size=size or tuple(self.inp.shape[1:3]), layout='nhwc', dtype='uint8',
                                   resize=resize or ('letterbox' if self._task == 'detect' else 'stretch'))
                              if self.inp.kind == 'image' else
                              prep_from_spec(self.inp.shape, self.inp.dtype, norm=norm or '01', size=size,
                                             resize=resize, task=self._task))
        self._max_bs = 1

    def _mk_model(self, compute_units='ALL', **kw):
        try: import coremltools as ct
        except ImportError as e:
            raise ImportError("anya needs coremltools for Core ML models: pip install 'anya[coreml]'") from e
        return ct.models.MLModel(self.model_path, compute_units=ct.ComputeUnit[compute_units], **kw)

    @property
    def spec(self) -> AttrDict:
        'What the model declares, as plain dicts.'
        return AttrDict(inputs=list(self.inputs), outputs=list(self.outputs), kind=self.kind)

    def _infer(self, x) -> list:
        if self._sess is None: raise RuntimeError('this model is closed')
        out = self._sess.predict({self.inp.name: self._as_input(x[0])})
        self._last = out
        return [np.asarray(out[o.name]) for o in self.outputs if o.name in out and not isinstance(out[o.name], dict)]

    def _as_input(self, a):
        'One preprocessed item as Core ML wants it: a PIL image for an image input, else an array.'
        if self.inp.kind != 'image': return a.astype('float32')
        from PIL import Image
        return Image.fromarray(a.astype('uint8'))

    def decode(self, outs, meta:dict, src=None, **kw) -> Pred:
        'Core ML classifiers answer with `{label: probability}`, which is already decoded.'
        d = getattr(self, '_last', None) or {}
        probs = next((v for v in d.values() if isinstance(v, dict)), None)
        if probs is not None:
            return Pred(src=src, task='classify', model=self.name,
                        preds=decode_class_dict(probs, kw.get('topk', self.topk)))
        return super().decode(outs, meta, src, **kw)
