"""One `Model` over every runtime, one `Pred` back, and the file moves that follow from a prediction.

Docs: https://vedicreader.github.io/anya/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% ../nbs/00_core.ipynb #1da02f56
from __future__ import annotations
import json, os, shutil
from importlib import import_module
from pathlib import Path

import numpy as np
from fastcore.all import AttrDict, L, store_attr

from .vision import (MEDIA_EXTS, IMG_EXTS, AUD_EXTS, VID_EXTS, AudioPrep, Prep, batch, decode_classify,
                         decode_detect_auto, decode_segment, load_audio, load_image, pool_embed, read_labels,
                         video_frames)

# %% auto #0
__all__ = ['runtimes', 'TASKS', 'EMBED_DIMS', 'NORMS', 'CHANNELS', 'is_loaded', 'item_src', 'items', 'Pred', 'Preds',
           'split_runtime', 'infer_runtime', 'resolve_runtime', 'get_runtime', 'dims', 'nobatch', 'infer_task',
           'chan_axis', 'prep_from_spec', 'Model', 'model_file', 'sidecar_labels', 'with_hub_defaults', 'load_model',
           'loaded_models', 'clear_models', 'safe_name', 'arrange']

# %% ../nbs/00_core.ipynb #c3c940e5
def is_loaded(o) -> bool:
    'Is `o` already pixels or bytes rather than something to read off disk?'
    return isinstance(o, (np.ndarray, bytes, bytearray)) or (hasattr(o, 'mode') and hasattr(o, 'size'))

def item_src(o) -> str|None:
    'A printable source for `o`, or None when it came in as pixels.'
    return None if is_loaded(o) else str(o)

def items(o,                      # a path, a folder, a glob, an iterable of any of those, or pixels
          types:str='image',      # 'image', 'audio', 'video', 'any', or an iterable of suffixes
          recurse:bool=True,      # walk subdirectories of a folder
          sort:bool=True,         # deterministic order, so a rerun matches the last run
          exclude=None            # paths to skip: a sorted output folder under the folder being read
         ) -> L:
    'Expand `o` into a flat `L` of things a model can be run on.'
    exts = _exts(types)
    if o is None: return L()
    if is_loaded(o): return L([o])
    if isinstance(o, (str, Path)):
        p = Path(o).expanduser()
        if p.is_dir():
            fs = L(p.rglob('*') if recurse else p.glob('*')).filter(lambda f: f.is_file() and f.suffix.lower() in exts)
        elif any(c in str(o) for c in '*?['): fs = L(Path().glob(str(o)))
        else: fs = L([p])
        fs = _drop_excluded(fs, exclude)
        return fs.sorted() if sort else fs
    return L(o).map(lambda x: items(x, types=types, recurse=recurse, sort=sort, exclude=exclude)).concat()

def _drop_excluded(fs, exclude) -> L:
    'Files under any of `exclude` are not items: this is what stops a second run reading its own output.'
    if not exclude: return fs
    ex = L(exclude if isinstance(exclude, (list, tuple, L)) else [exclude]).map(lambda p: str(Path(p).expanduser().absolute()))
    return fs.filter(lambda f: not any(str(Path(f).absolute()).startswith(e + os.sep) for e in ex))

def _exts(types) -> set:
    if types in (None, 'any', 'all'): return MEDIA_EXTS
    if isinstance(types, str): return {'image': IMG_EXTS, 'audio': AUD_EXTS, 'video': VID_EXTS}[types]
    return {e if e.startswith('.') else '.'+e for e in types}

# %% ../nbs/00_core.ipynb #ff68df75
class Pred(AttrDict):
    'One result: what it ran on, which model, and the task-shaped payload.'
    @property
    def label(self) -> str|None:
        'The single most useful label: top class, biggest object, or largest segment.'
        if self.get('error'): return None
        for k in ('preds', 'objects', 'classes'):
            if self.get(k): return self[k][0]['label']
        return self.get('text')

    @property
    def score(self) -> float|None:
        'Confidence behind `label`.'
        for k in ('preds', 'objects'):
            if self.get(k): return self[k][0]['score']
        if self.get('classes'): return self['classes'][0]['frac']
        return None

    def json(self) -> dict:
        'A JSON-safe copy: arrays are replaced by their shape.'
        return {k: (dict(shape=list(np.shape(v)), dtype=str(np.asarray(v).dtype)) if isinstance(v, np.ndarray) else v)
                for k, v in self.items()}

    def _repr_markdown_(self):
        h = f"**{self.label}**" + (f" ({self.score:.3f})" if self.score is not None else '')
        if self.get('error'): h = f"**error**: {self['error']}"
        rows = [f"- {o['label']} {o['score']:.3f} {o.get('box','')}" for o in (self.get('objects') or [])[:8]]
        rows += [f"- {p['label']} {p['score']:.3f}" for p in (self.get('preds') or [])[1:6]]
        rows += [f"- {c['label']} {c['frac']:.1%}" for c in (self.get('classes') or [])[1:6]]
        return '\n'.join([f"`{self.get('src') or 'array'}` → {h}", ''] + rows)

# %% ../nbs/00_core.ipynb #7a567857
class Preds(L):
    'The results of one run, with the summaries a caller actually asks for.'
    @property
    def labels(self) -> L:
        'The one label per item, in order. `attrgot` would read the dict key, not the property.'
        return L(p.label for p in self)
    @property
    def ok(self) -> Preds: return self.filter(lambda p: not p.get('error'))
    @property
    def failed(self) -> Preds: return self.filter(lambda p: p.get('error'))

    def counts(self) -> dict:
        'How many items got each label, most common first.'
        c = {}
        for l in self.ok.labels: c[l] = c.get(l, 0) + 1
        return dict(sorted(c.items(), key=lambda t: -t[1]))

    def above(self, score:float) -> Preds:
        'Only the predictions the model was at least `score` confident about.'
        return self.ok.filter(lambda p: (p.score or 0) >= score)

    def by_label(self) -> dict:
        'Group into `{label: Preds}`.'
        d = {}
        for p in self.ok: d.setdefault(p.label, Preds()).append(p)
        return d

    def records(self) -> list:
        'JSON-safe dicts, one per item.'
        return [p.json() for p in self]

    def save(self, path) -> Path:
        'Write `records()` to a JSON file.'
        p = Path(path); p.write_text(json.dumps(self.records(), indent=1)); return p

    def _repr_markdown_(self):
        n = len(self)
        head = f"{n} item{'s' if n != 1 else ''}" + (f", {len(self.failed)} failed" if self.failed else '')
        rows = [f"| `{Path(p.get('src') or 'array').name}` | {p.label} | {p.score:.3f} |" if p.score is not None
                else f"| `{Path(p.get('src') or 'array').name}` | {p.label or p.get('error')} | |" for p in self[:20]]
        tbl = ['', '| item | label | score |', '|---|---|---|'] + rows + (['| … | | |'] if n > 20 else [])
        return '\n'.join([head] + tbl)

# %% ../nbs/00_core.ipynb #379eb02a
runtimes = {'onnx':   ('anya.onnx',   'OnnxModel'),
            'litert': ('anya.litert', 'LitertModel'),
            'coreml': ('anya.apple',  'CoreMLModel')}

# checked in order, so a suffix wins over a word appearing anywhere in a repo id
_pats = {'litert': ('.tflite', '.lite', 'litert', 'tflite'),
         'onnx':   ('.onnx', '.ort', 'onnx'),
         'coreml': ('.mlpackage', '.mlmodel', '.mlmodelc', 'coreml', 'core-ml')}

def split_runtime(model):
    "Split `'runtime/model'` into `(runtime, model)`; the prefix must name a known runtime, else `(None, model)`."
    if isinstance(model, str) and '/' in model:
        b, m = model.split('/', 1)
        if b in runtimes: return b, m
    return None, model

def infer_runtime(model):
    "Guess a runtime from the shape of a model id or path (`.tflite` vs `.onnx`), else `None`."
    s = str(model or '').lower()
    if not s: return None
    return next((b for b, ps in _pats.items() if any(p in s for p in ps)), None)

def resolve_runtime(model=None, runtime=None, model_path=None):
    "Resolve `(runtime, model)`; `runtime` is `None` when only the hub can say what a repo ships."
    pre, model = split_runtime(model)
    nm = runtime or pre or infer_runtime(model) or infer_runtime(model_path)
    if nm is not None and nm not in runtimes:
        raise ValueError(f"Unknown runtime {nm!r}; known runtimes: {', '.join(runtimes)}.")
    return nm, model

def _runtime_mod(nm):
    "Import the runtime module for `nm`, with an actionable error when its wheel is missing."
    try: return import_module(runtimes[nm][0])
    except ImportError as e:
        raise ImportError(f"The {nm!r} runtime is unavailable ({e}). "
                          f"Install it with: pip install 'anya[{nm}]'") from None

def get_runtime(nm):
    "The `Model` subclass for runtime `nm` (imports the runtime module lazily)."
    return getattr(_runtime_mod(nm), runtimes[nm][1])

# %% ../nbs/00_core.ipynb #b3492430
TASKS = ('classify', 'detect', 'segment', 'embed')

# a single vector this wide, with no labels to go with it, is a feature vector rather than classes
EMBED_DIMS = {64, 128, 192, 256, 320, 384, 512, 640, 768, 896, 1024, 1152, 1280, 1408, 1536, 2048, 4096}

def dims(shape) -> list:
    'The concrete dimensions of a declared shape; symbolic axes (a named batch) drop out.'
    return [d for d in (d if isinstance(d, int) and d > 0 else None for d in shape) if d]

def nobatch(shape) -> list:
    'A declared shape without its batch axis, which is a 1 or a name.'
    s = list(shape)
    return s[1:] if len(s) > 1 and (s[0] == 1 or not isinstance(s[0], int)) else s

def infer_task(shapes,          # output shapes the model declares, in order
               labels=None,     # class names, when the model or the caller supplied them
               names=None       # output tensor names, which often say it outright
              ) -> str:
    'Guess the task from output shapes: four heads is a detector, a grid of classes is a segmenter.'
    # 'logits' is what a classifier and a segmenter both call their output, so it says nothing
    ns = ' '.join(str(n).lower() for n in (names or []))
    for k, t in (('box', 'detect'), ('mask', 'segment'), ('segment', 'segment'),
                 ('embed', 'embed'), ('feature', 'embed'), ('hidden', 'embed')):
        if k in ns: return t
    shapes = L(shapes)
    s = nobatch(shapes[0]) if len(shapes) else []
    if len(shapes) >= 3:
        if list(shapes[0])[-1] == 4: return 'detect'        # boxes / classes / scores / count
        if len(s) <= 1: return 'classify'                   # yamnet: scores, embeddings, spectrogram
        raise ValueError(f'{len(shapes)} outputs of shape {[list(x) for x in shapes[:4]]}: anya cannot tell '
                         'what this model does. Pass task= to say, or a prep= and read the outputs yourself.')
    if len(s) >= 3: return 'segment'                       # a class per pixel, C,H,W or H,W,C
    d = dims(s)
    if len(d) == 2:
        a, b = sorted(d)
        return 'detect' if b >= 100 and a <= 512 else 'classify'
    if len(d) == 1 and labels is None and d[0] in EMBED_DIMS: return 'embed'
    return 'classify'

# %% ../nbs/00_core.ipynb #4307c356
from .vision import BILINEAR, IMAGENET

NORMS = {'01':       ((0., 0., 0.), (1., 1., 1.)),        # pixels in 0..1
         'imagenet': IMAGENET,                            # torchvision and timm exports
         'signed':   ((.5, .5, .5), (.5, .5, .5)),        # pixels in -1..1, most TF exports
         'none':     ((0., 0., 0.), (1., 1., 1.))}        # raw 0..255

CHANNELS = (1, 3, 4)

def chan_axis(shape) -> int:
    'Which axis of an image input holds the channels: 1 for NCHW, -1 for NHWC.'
    # optimum exports every axis symbolic and names them, so the name is all there is to read
    named = lambda i: (nm := str(shape[i]).lower()) == 'c' or 'chan' in nm
    if named(1): return 1
    if named(-1): return -1
    return 1 if (shape[1] in CHANNELS and shape[-1] not in CHANNELS) else -1

def prep_from_spec(shape,                 # the input tensor shape the model declares
                   dtype:str='float32',   # its dtype
                   norm='01',             # a NORMS name, or an explicit (mean, std)
                   size:tuple=None,       # size for the axes the shape leaves symbolic
                   resize:str=None,       # 'stretch', 'letterbox', 'center_crop'
                   crop_pct:float=None,   # fraction of the short side kept by 'center_crop'
                   resample:int=None,     # PIL resample filter; bilinear unless the config says otherwise
                   quant:tuple=None,      # (scale, zero_point) for a quantised input
                   task:str=None,         # only used to pick a default size and resize mode
                   layout:str=None,       # override the channel-axis guess
                   bgr:bool=False
                  ):
    'The `Prep` (or `AudioPrep`) that one input signature calls for.'
    s = list(shape)
    if len(s) <= 2:                                        # (batch, samples) or (samples,): a waveform
        n = dims(s)
        return AudioPrep(samples=(n[-1] if n and n[-1] > 16 else None), dtype=dtype,
                         layout='nt' if len(s) == 2 else 't')
    d = [x if isinstance(x, int) and x > 0 else None for x in s]
    lay = layout or ('nchw' if chan_axis(s) == 1 else 'nhwc')
    hw = (d[2], d[3]) if lay == 'nchw' else (d[1], d[2])
    dflt = 640 if task == 'detect' else 224
    # a size the graph states outright wins: it is the only one the graph will accept
    size = tuple(a or b or dflt for a, b in zip(hw, tuple(size) if size else (None, None)))
    mean, std = NORMS[norm] if isinstance(norm, str) else norm
    scale = 1.0 if norm == 'none' else 1/255
    return Prep(size=size, layout=lay, dtype=dtype, scale=scale, mean=mean, std=std, crop_pct=crop_pct,
                resample=resample or BILINEAR, quant=quant, bgr=bgr,
                resize=resize or ('letterbox' if task == 'detect' else 'stretch'))

# %% ../nbs/00_core.ipynb #f7d2571c
class Model:
    "Runtime-agnostic model: `Model(name)` dispatches to the onnx/litert/coreml subclass."
    _runtime = None

    def __new__(cls, model=None, *, runtime=None, model_path=None, **kw):
        # `__new__` only picks the class: Python then calls the subclass `__init__` with the original
        # arguments, so anything resolved here would be thrown away. `model_file` re-resolves, cached.
        if cls is not Model: return super().__new__(cls)
        nm, m = resolve_runtime(model, runtime, model_path)
        if nm is None:
            from anya.hub import resolve_model
            nm = resolve_model(m, file=kw.get('file'), revision=kw.get('revision'))[0]
        return super().__new__(get_runtime(nm))

    def _setup(self, model=None, model_path=None, task=None, labels=None, prep=None,
               topk:int=5, conf:float=0.25, iou:float=0.45, meta:dict=None):
        'Shared init tail: store the knobs every task shares and normalise the labels.'
        _, model = split_runtime(model)
        store_attr('model,model_path,topk,conf,iou', self)
        self.labels = read_labels(labels)
        self.meta = dict(meta or {})
        self._task, self._prep = task, prep
        return model

    @property
    def runtime(self) -> str: return self._runtime
    @property
    def task(self) -> str: return self._task
    @property
    def prep(self) -> Prep: return self._prep
    @property
    def name(self) -> str: return str(self.model or self.model_path)

    def __repr__(self):
        n = f', {len(self.labels)} labels' if self.labels else ''
        return f'{type(self).__name__}({Path(self.name).name}, runtime={self.runtime}, task={self.task}{n})'

    def _infer(self, x) -> list:
        'Run one preprocessed batch; returns the output arrays in declared order.'
        raise NotImplementedError

    @property
    def modality(self) -> str:
        "'audio' when the model wants a waveform, else 'image'."
        return 'audio' if isinstance(self.prep, AudioPrep) else 'image'

    def _load_one(self, o):
        'Read one item into the array this model takes.'
        if is_loaded(o) and not isinstance(o, (bytes, bytearray)) and self.modality == 'audio': return np.asarray(o, np.float32)
        return load_audio(o, self.prep.sr)[0] if self.modality == 'audio' else load_image(o)

    def decode(self, outs, meta:dict, src=None, **kw) -> Pred:
        'Turn raw output arrays into a `Pred` for this model\'s task.'
        d = dict(src=src, task=self.task, model=self.name)
        t, o0 = self.task, np.asarray(outs[0])
        if t == 'classify': return Pred(d, preds=decode_classify(o0, self.labels, kw.get('topk', self.topk)))
        if t == 'detect': return Pred(d, objects=decode_detect_auto(outs, self.labels, meta=meta,
                                                                   conf=kw.get('conf', self.conf), iou=kw.get('iou', self.iou)))
        if t == 'segment': return Pred(d, **decode_segment(o0, self.labels, meta=meta))
        if t == 'embed': return Pred(d, vec=pool_embed(o0))
        return Pred(d, raw=[np.asarray(o) for o in outs])

    def predict(self, o, **kw) -> Pred:
        'Run the model on one item.'
        a = self._load_one(o)
        x, ms = batch([a], self.prep)
        return self.decode(self._infer(x), ms[0], item_src(o), **kw)

    def predict_all(self, o,                    # anything `items` accepts
                    bs:int=None,                # batch size; the model's own limit caps it
                    on_error:str='skip',        # 'skip' records the error and carries on, 'raise' stops
                    types:str=None,             # which files a folder contributes; defaults to the model's modality
                    exclude=None,               # paths to skip, such as the folder the results are being written to
                    **kw
                   ) -> Preds:
        'Run the model over a folder, a list or a glob.'
        xs = items(o, types=types or self.modality, exclude=exclude)
        bs = min(bs or self.max_bs, self.max_bs)
        out = Preds()
        for i in range(0, len(xs), bs):
            chunk = xs[i:i+bs]
            res, loaded = [None]*len(chunk), []
            for k, x in enumerate(chunk):
                try: loaded.append((k, x, self._load_one(x)))       # one unreadable file, not one lost batch
                except Exception as e:
                    if on_error == 'raise': raise
                    res[k] = self._on_error(x, e)
            if loaded:
                try:
                    arr, ms = batch([a for _, _, a in loaded], self.prep)
                    outs = self._infer(arr)
                    for j, (k, x, _) in enumerate(loaded):
                        res[k] = self.decode([np.asarray(o)[j:j+1] for o in outs], ms[j], item_src(x), **kw)
                except Exception as e:
                    if on_error == 'raise': raise
                    for k, x, _ in loaded: res[k] = self._on_error(x, e)
            out += [r for r in res if r is not None]
        return out

    def predict_video(self, path,                 # one video file
                      every:float=1.0,            # seconds between sampled frames
                      max_frames:int=None,
                      **kw
                     ) -> Preds:
        'Sample frames out of a video and run the model on each; every `Pred` carries its timestamp.'
        out = Preds()
        for t, f in video_frames(path, every=every, max_frames=max_frames):
            p = self.predict(f, **kw)
            p['src'], p['t'] = f'{path}#t={t:.2f}', round(t, 3)
            out.append(p)
        return out

    def _on_error(self, x, e) -> Pred:
        return Pred(src=item_src(x), task=self.task, model=self.name, error=f'{type(e).__name__}: {e}')

    @property
    def max_bs(self) -> int:
        'Largest batch the loaded graph accepts; 1 unless the runtime says otherwise.'
        return getattr(self, '_max_bs', 1)

    def __call__(self, o, **kw):
        'One item in, one `Pred` out; a folder or list in, `Preds` out.'
        if is_loaded(o) or (isinstance(o, (str, Path)) and not Path(str(o)).is_dir() and not any(c in str(o) for c in '*?[')):
            return self.predict(o, **kw)
        return self.predict_all(o, **kw)

    def close(self):
        'Release the graph. A closed model raises if called again.'
        self._sess = None
    def __enter__(self): return self
    def __exit__(self, *a): self.close()

# %% ../nbs/00_core.ipynb #1d0afc96
def model_file(model=None,       # a path or a hub repo id
               model_path=None,  # an explicit file, which wins
               file:str=None,    # which file inside a repo, when the repo ships several
               revision:str=None
              ) -> Path:
    'The local file a runtime should open, downloading it from the hub the first time if needed.'
    if model_path: return Path(model_path).expanduser()
    p = Path(str(model)).expanduser()
    if p.exists(): return p
    from anya.hub import resolve_model
    return Path(resolve_model(str(model), file=file, revision=revision)[1])

# %% ../nbs/00_core.ipynb #a5ad0bf0
def sidecar_labels(path) -> Path|None:
    'A labels file beside the weights or up at the repo root, which is how most exports ship class names.'
    p = Path(path)
    if (c := p.with_suffix('.txt')).exists(): return c
    named = lambda f: any(w in f.name.lower() for w in ('label', 'class'))    # labels_yamnet.txt, coco_labels.txt
    for d in list(p.parents)[:3]:            # the hub cache mirrors the repo, so a root file is a level up
        if (hits := L(d.glob('*.txt')).filter(named).sorted()): return hits[0]
        if (c := d/'config.json').exists(): return c
    return None

def with_hub_defaults(path,           # the local weights file
                      labels=None,    # class names, if the caller has them
                      **kw            # anything `prep_from_spec` takes; None means unset
                     ) -> tuple:
    'Returns `(labels, prep keywords)`, filling whatever the caller left unset from the configs beside `path`.'
    kw = {k: v for k, v in kw.items() if v is not None}
    try: from anya.hub import model_config, prep_kwargs
    except ImportError: return labels, kw
    c = model_config(path)
    return (labels if labels is not None else read_labels(c.config), {**prep_kwargs(c.preprocessor), **kw})

# %% ../nbs/00_core.ipynb #88e792fa
_models = {}

def load_model(model=None, **kw) -> Model:
    'A cached `Model`, expanding an alias from the registry; the same arguments return the same object.'
    try:
        from anya.hub import resolve_alias
        if (a := resolve_alias(model)): model, kw = a['model'], {**{x: y for x, y in a.items() if x != 'model'}, **kw}
    except ImportError: pass
    k = (str(model), tuple(sorted((a, str(b)) for a, b in kw.items())))
    if k not in _models: _models[k] = Model(model, **kw)
    return _models[k]

def loaded_models() -> L:
    'What `load_model` is currently holding open.'
    return L(_models.values())

def clear_models():
    'Close and drop every cached model.'
    for m in _models.values():
        try: m.close()
        except Exception: pass
    _models.clear()

# %% ../nbs/00_core.ipynb #ca032161
def safe_name(s:str, mx:int=60) -> str:
    'A label as a directory name: no separators, no surprises.'
    out = ''.join(c if (c.isalnum() or c in ' -_') else '_' for c in str(s)).strip().replace(' ', '_')
    return (out[:mx] or 'unlabelled').strip('._')

def arrange(preds:Preds,             # what a model returned
            dest,                    # directory to build under
            how:str='copy',          # 'copy', 'move', or 'link' (a hard link, so nothing is duplicated)
            min_score:float=0.0,     # anything less confident goes to `other`
            other:str='unsorted',    # folder for low-confidence and failed items
            dry_run:bool=True,       # print the plan and change nothing
            depth:int=1              # 1 = dest/label/file, 2 = dest/label/sub-label/file for hierarchical names
           ) -> AttrDict:
    'Sort the files behind `preds` into `dest/<label>/`, returning the plan and what was done.'
    dest = Path(dest).expanduser()
    plan, seen = [], set()
    for p in preds:
        src = p.get('src')
        if not src: continue
        lab = p.label if (not p.get('error') and (p.score or 0) >= min_score) else None
        parts = [safe_name(x) for x in str(lab).split('/')[:depth]] if lab else [safe_name(other)]
        d = dest.joinpath(*parts)/Path(src).name
        n = 1
        while str(d) in seen or (d.exists() and not dry_run and Path(src).resolve() != d.resolve()):
            d = d.with_name(f'{Path(src).stem}_{n}{Path(src).suffix}'); n += 1
        seen.add(str(d))
        plan.append(dict(src=str(src), dst=str(d), label=lab))
    done = 0
    if not dry_run:
        for a in plan:
            Path(a['dst']).parent.mkdir(parents=True, exist_ok=True)
            _place(a['src'], a['dst'], how); done += 1
    return AttrDict(dest=str(dest), how=how, dry_run=dry_run, n=len(plan), moved=done,
                    labels=sorted({a['label'] for a in plan if a['label']}), plan=plan)

def _place(src, dst, how):
    if how == 'move': shutil.move(src, dst)
    elif how == 'link':
        try: os.link(src, dst)
        except OSError: shutil.copy2(src, dst)     # a hard link cannot cross a filesystem
    else: shutil.copy2(src, dst)
