"""Find a model, fetch it, and work out what its author expected you to do to a picture first.

Docs: https://vedicreader.github.io/anya/hub.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_hub.ipynb.

# %% ../nbs/05_hub.ipynb #d9ab5c67
from __future__ import annotations
import json, os, re
from functools import lru_cache
from pathlib import Path

from fastcore.all import AttrDict, L

from .core import infer_runtime, runtimes

# %% auto #0
__all__ = ['WEIGHT_EXTS', 'SIDECARS', 'PIPELINES', 'weight_files', 'file_runtime', 'dflt_prefer', 'score_file', 'pick_file',
           'prep_kwargs', 'repo_files', 'fetch', 'fetch_sidecars', 'resolve_model', 'model_config', 'find_models',
           'web_models', 'registry_path', 'aliases', 'alias', 'resolve_alias']

# %% ../nbs/05_hub.ipynb #5468ec5e
WEIGHT_EXTS = {'.onnx': 'onnx', '.ort': 'onnx', '.tflite': 'litert', '.lite': 'litert',
               '.mlpackage': 'coreml', '.mlmodel': 'coreml', '.mlmodelc': 'coreml'}

def weight_files(files) -> L:
    'Every file in `files` that some runtime can open.'
    return L(files).filter(lambda f: any(str(f).lower().endswith(e) for e in WEIGHT_EXTS))

def file_runtime(f) -> str|None:
    'Which runtime opens `f`, by suffix.'
    s = str(f).lower()
    return next((r for e, r in WEIGHT_EXTS.items() if s.endswith(e)), None)

def dflt_prefer() -> tuple:
    'Runtime preference for this machine: Core ML on a Mac, then ONNX, then LiteRT.'
    import sys
    return ('coreml', 'onnx', 'litert') if sys.platform == 'darwin' else ('onnx', 'litert', 'coreml')

def score_file(f, prefer=None) -> tuple:
    'Sort key for a candidate weights file: runtime preference first, then how plain the name is.'
    prefer = prefer or dflt_prefer()
    rt = file_runtime(f)
    s, name = str(f).lower(), Path(str(f)).stem.lower()
    rank = prefer.index(rt) if rt in prefer else len(prefer)
    plain = 0 if name in ('model', 'model_float32', Path(str(f)).parent.name.lower()) else 1
    deep = s.count('/')                                   # a file at the root beats one buried in a variant folder
    return (rank, plain, deep, len(s))

def pick_file(files,            # every path in the repo
              prefer=None,      # runtime order, e.g. ('litert','onnx')
              pat:str=None      # only consider files matching this regex
             ) -> str|None:
    'The one weights file to download, or None when the repo ships none.'
    c = weight_files(files)
    if pat: c = c.filter(lambda f: re.search(pat, str(f), re.I))
    if isinstance(prefer, str): prefer = (prefer,) + tuple(r for r in dflt_prefer() if r != prefer)
    return min(c, key=lambda f: score_file(f, prefer), default=None)

# %% ../nbs/05_hub.ipynb #41dea228
def _hw(sz) -> tuple|None:
    'A `size` field as `(h, w)`: it is an int, a height/width pair, or a shortest edge.'
    if isinstance(sz, int): return (sz, sz)
    if not isinstance(sz, dict): return None
    h, w = sz.get('height'), sz.get('width')
    if h and w: return (int(h), int(w))
    return (int(s), int(s)) if (s := sz.get('shortest_edge')) else None

def prep_kwargs(cfg:dict) -> dict:
    'Turn a `preprocessor_config.json` into `size=` / `norm=` / `resize=` / `crop_pct=` for a `Model`.'
    if not cfg: return {}
    out, size, crop = {}, _hw(cfg.get('size')), _hw(cfg.get('crop_size'))
    if cfg.get('do_center_crop'): out['resize'] = 'center_crop'
    # size 256 with crop_size 224 means resize the short side to 256, then crop 224 out of the middle.
    # SpotLab/YOLOv8Detection asks for a 640 crop out of a 256 short side, which is not a crop.
    if crop and size and crop[0] < size[0]: out['crop_pct'] = round(crop[0]/size[0], 4)
    if (sz := (crop if cfg.get('do_center_crop') else None) or size or crop): out['size'] = sz
    m, s = cfg.get('image_mean'), cfg.get('image_std')
    if m and s: out['norm'] = (tuple(float(x) for x in m), tuple(float(x) for x in s))
    # bicubic against bilinear moved top-1 on one of five photos, so the filter is worth carrying
    if isinstance(cfg.get('resample'), int): out['resample'] = cfg['resample']
    return out

# %% ../nbs/05_hub.ipynb #d73a74f2
SIDECARS = ('config.json', 'preprocessor_config.json', 'labels.txt', 'classes.txt', 'labelmap.txt')

def _api(token=None):
    try: from huggingface_hub import HfApi
    except ImportError as e:
        raise ImportError("anya needs huggingface-hub to fetch a model by repo id: pip install 'anya[hub]'") from e
    return HfApi(token=token)

def repo_files(repo_id:str, revision:str=None, token=None) -> L:
    'Every file in a Hub repo.'
    return L(_api(token).list_repo_files(repo_id, revision=revision))

def fetch(repo_id:str,          # a Hub repo id
          filename:str,         # a path inside the repo
          revision:str=None,
          token=None
         ) -> Path:
    'Download one file from the Hub (cached) and return the local path.'
    from huggingface_hub import hf_hub_download
    return Path(hf_hub_download(repo_id, filename, revision=revision, token=token))

def fetch_sidecars(repo_id:str, files, dest:Path, revision:str=None, token=None) -> dict:
    'Download the config and label files that sit beside the weights, ignoring any that 404.'
    out = {}
    for n in SIDECARS:
        hit = next((f for f in files if str(f).rsplit('/', 1)[-1] == n), None)
        if not hit: continue
        try: out[n] = fetch(repo_id, hit, revision=revision, token=token)
        except Exception: pass          # a listed file can still be gated or moved
    return out

# %% ../nbs/05_hub.ipynb #fa4d9824
@lru_cache(maxsize=64)
def resolve_model(repo_id:str,        # a Hub repo id, or a local path
                  file:str=None,      # a filename inside the repo, when you know it
                  revision:str=None,
                  prefer=None,        # runtime order, e.g. 'litert'
                  token=None
                 ) -> tuple:
    'Work out `(runtime, local path)` for a Hub repo, downloading the weights and their sidecars.'
    p = Path(repo_id).expanduser()
    if p.exists(): return (infer_runtime(p), str(p))
    files = repo_files(repo_id, revision=revision, token=token)
    pick = file or pick_file(files, prefer=prefer)
    if pick is None: raise ValueError(
        f'{repo_id} ships no file anya can run (looked for {", ".join(WEIGHT_EXTS)}). '
        f'It has: {", ".join(map(str, files[:12]))}')
    path = fetch(repo_id, pick, revision=revision, token=token)
    fetch_sidecars(repo_id, files, path.parent, revision=revision, token=token)
    return (file_runtime(pick), str(path))

def model_config(path) -> AttrDict:
    'The `config.json` and `preprocessor_config.json` cached next to a downloaded model.'
    d, out = Path(path).parent, {}
    for _ in range(3):                              # the hub cache nests the file under snapshots/<sha>/
        for n in ('config.json', 'preprocessor_config.json'):
            if (d/n).exists() and n not in out:
                try: out[n] = json.loads((d/n).read_text())
                except Exception: pass
        d = d.parent
    return AttrDict(config=out.get('config.json', {}), preprocessor=out.get('preprocessor_config.json', {}))

# %% ../nbs/05_hub.ipynb #ffaa375f
PIPELINES = {'classify': 'image-classification', 'detect': 'object-detection',
             'segment': 'image-segmentation', 'embed': 'image-feature-extraction'}

def find_models(query:str,          # what the model should do, in words
                task:str=None,      # 'classify', 'detect', 'segment', 'embed'
                runtime:str=None,   # only repos with a file this runtime can open
                n:int=10,
                token=None
               ) -> L:
    'Search the Hub for models anya can run: the whole phrase first, then each word, most downloaded first.'
    kw = dict(sort='downloads', limit=max(n*3, 30))
    if task: kw['pipeline_tag'] = PIPELINES.get(task, task)
    if runtime: kw['filter'] = {'onnx': 'onnx', 'litert': 'tflite', 'coreml': 'coreml'}[runtime]
    # the Hub matches `search` against the repo id, so 'bird classifier' finds none of what 'bird' finds
    found = {}
    for q in dict.fromkeys([query, *query.split()]):
        for m in _api(token).list_models(search=q, **kw):
            found.setdefault(m.id, AttrDict(id=m.id, downloads=getattr(m, 'downloads', 0),
                                            task=getattr(m, 'pipeline_tag', None), likes=getattr(m, 'likes', 0)))
        if len(found) >= n: break
    return L(found.values())[:n]        # in search order: 'bird' outranks the more downloaded 'classifier'

def web_models(query:str, n:int=5) -> L:
    'Ask the open web for HuggingFace models, for when the Hub API is not reachable.'
    try: from fossick import search
    except ImportError as e:
        raise ImportError('web_models needs fossick: pip install fossick') from e
    hits = search(f'{query} huggingface model onnx OR tflite', n=n*3)
    ids = L(re.findall(r'huggingface\.co/([\w.\-]+/[\w.\-]+)', ' '.join(h.get('href', '') for h in hits)))
    return ids.unique()[:n].map(lambda i: AttrDict(id=i, downloads=None, task=None, likes=None))

# %% ../nbs/05_hub.ipynb #e033f664
def registry_path() -> Path:
    'Where aliases live: `$ANYA_HOME/models.json`, else `~/.anya/models.json`.'
    return Path(os.environ.get('ANYA_HOME', Path.home()/'.anya')).expanduser()/'models.json'

def aliases() -> dict:
    'Every alias defined on this machine.'
    p = registry_path()
    if not p.exists(): return {}
    try: return json.loads(p.read_text())
    except Exception: return {}

def alias(name:str,            # the short name to use from now on
          repo:str=None,       # the repo id or path it stands for; None deletes it
          **kw                 # file=, labels=, norm=, size=, task=, anything Model takes
         ) -> dict:
    'Define (or with `repo=None`, delete) a short name for a model, saved for later sessions.'
    d, p = aliases(), registry_path()
    if repo is None: d.pop(name, None)
    else: d[name] = dict(model=repo, **kw)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(d, indent=1))
    return d

def resolve_alias(name) -> dict|None:
    'The `Model` keyword arguments an alias stands for, or None.'
    return aliases().get(str(name))
