"""`.tflite` models over LiteRT, including quantised ones, with the labels read out of the file.

Docs: https://vedicreader.github.io/anya/litert.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_litert.ipynb.

# %% ../nbs/03_litert.ipynb #55cba59f
from __future__ import annotations
import zipfile
from pathlib import Path

import numpy as np
from fastcore.all import AttrDict, L

from .core import Model, model_file, sidecar_labels
from .vision import read_labels

# %% auto #0
__all__ = ['tflite_labels', 'dequant', 'norm_from_quant', 'LitertModel']

# %% ../nbs/03_litert.ipynb #5dc52f01
def tflite_labels(path) -> L|None:
    'Class names from the metadata zip appended to a `.tflite` file, if it has one.'
    if not zipfile.is_zipfile(path): return None
    with zipfile.ZipFile(path) as z:
        names = [n for n in z.namelist() if n.lower().endswith(('.txt', '.csv'))]
        pick = next((n for n in names if 'label' in n.lower()), None) or next(iter(names), None)
        if pick is None: return None
        return read_labels([l for l in z.read(pick).decode('utf-8', 'replace').split('\n') if l.strip()])

# %% ../nbs/03_litert.ipynb #ee48217e
def dequant(a, q) -> np.ndarray:
    'Undo a tensor\'s quantisation; a float tensor passes through.'
    s, z = (q or (0.0, 0))[:2]
    return np.asarray(a, np.float32) if not s else (np.asarray(a, np.float32) - z) * s

def norm_from_quant(q, dtype) -> str|None:
    "The pixel range a quantised input implies: 0..1 is `'01'`, -1..1 is `'signed'`, 0..255 is `'none'`."
    s, z = (q or (0.0, 0))[:2]
    if not s or not np.issubdtype(np.dtype(dtype), np.integer): return None
    i = np.iinfo(np.dtype(dtype))
    lo, hi = (i.min - z)*s, (i.max - z)*s
    if abs(lo + 1) < 0.1 and abs(hi - 1) < 0.1: return 'signed'
    if abs(lo) < 0.05 and abs(hi - 1) < 0.1: return '01'
    if hi > 100: return 'none'
    return None

# %% ../nbs/03_litert.ipynb #0d6c8bf2
class LitertModel(Model):
    'A `.tflite` graph as a `Model`: shapes, quantisation and labels all come out of the file.'
    _runtime = 'litert'

    def __init__(self,
                 model=None,             # a path to a .tflite file, or a hub repo id
                 *,
                 runtime:str=None,       # ignored; `Model` has already dispatched on it
                 model_path=None,
                 file:str=None,          # which file to take from a repo that ships several
                 revision:str=None,
                 task:str=None,
                 labels=None,            # overrides whatever the file's metadata says
                 norm=None,              # None reads the pixel range off the quantisation; else a NORMS name
                 size:tuple=None,
                 resize:str=None,
                 crop_pct:float=None,    # fraction of the short side 'center_crop' keeps
                 resample:int=None,      # PIL resample filter, 2 bilinear or 3 bicubic
                 prep=None,
                 topk:int=5, conf:float=0.25, iou:float=0.45,
                 threads:int=None,       # interpreter threads; LiteRT's default is all cores
                 max_bs:int=1,           # >1 asks the interpreter to resize its input tensor
                 interp=None,            # an already-built Interpreter to reuse
                 **kw):
        model = self._setup(model, task=task, labels=labels, topk=topk, conf=conf, iou=iou)
        self.model_path = str(model_file(model, model_path, file=file, revision=revision))
        self._sess = interp or self._mk_interp(threads, **kw)
        self._read_spec()
        self._finish(task, prep, size=size, resize=resize, crop_pct=crop_pct, resample=resample,
                     norm=None if norm == 'auto' else norm)
        self._max_bs = self._resize_batch(max_bs)

    def _own_labels(self): return tflite_labels(self.model_path) or sidecar_labels(self.model_path)

    def _mk_prep(self, **pk):
        'The input quantisation also says what pixel range the model was trained on.'
        pk.setdefault('norm', norm_from_quant(self.inp.quant, self.inp.dtype) or '01')
        return super()._mk_prep(quant=self.inp.quant, **pk)

    def _mk_interp(self, threads=None, **kw):
        try: from ai_edge_litert.interpreter import Interpreter
        except ImportError as e:
            raise ImportError("anya needs LiteRT for .tflite models: pip install 'anya[litert]'") from e
        i = Interpreter(model_path=self.model_path, num_threads=threads, **kw)
        i.allocate_tensors()
        return i

    def _read_spec(self):
        'Tensor details, with quantisation kept as `(scale, zero_point)` or None.'
        f = lambda d: AttrDict(name=d['name'], index=d['index'], shape=[int(x) for x in d['shape']],
                               dtype=np.dtype(d['dtype']).name, quant=(tuple(d['quantization'])
                                                                       if d['quantization'][0] else None))
        self.inputs = L(self._sess.get_input_details()).map(f)
        self.outputs = L(self._sess.get_output_details()).map(f)
        if len(self.inputs) > 1: raise ValueError(
            f'{Path(self.model_path).name} takes {len(self.inputs)} inputs; anya drives single-input graphs.')
        self.inp = self.inputs[0]

    def _resize_batch(self, n:int) -> int:
        'Ask the interpreter for a batch of `n`, falling back to 1 when the graph will not take it.'
        if n <= 1: return 1
        try:
            self._sess.resize_tensor_input(self.inp.index, [n] + self.inp.shape[1:], strict=False)
            self._sess.allocate_tensors()
            self._read_spec()
            return n
        except Exception:
            self._sess.resize_tensor_input(self.inp.index, self.inp.shape, strict=False)
            self._sess.allocate_tensors()
            return 1

    @property
    def spec(self) -> AttrDict:
        'What the graph declares, as plain dicts.'
        return AttrDict(inputs=list(self.inputs), outputs=list(self.outputs))

    def _infer(self, x) -> list:
        if self._sess is None: raise RuntimeError('this model is closed')
        n = len(x)
        if n != self.inp.shape[0]: self._resize_batch(n)
        self._sess.set_tensor(self.inp.index, x.astype(self.inp.dtype, copy=False))
        self._sess.invoke()
        return [dequant(self._sess.get_tensor(o.index), o.quant) for o in self.outputs]
