"""`Model('yolo11n.onnx')` over ONNX Runtime, with preprocessing read off the graph.

Docs: https://vedicreader.github.io/anya/onnx.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_onnx.ipynb.

# %% ../nbs/02_onnx.ipynb #1198dba9
from __future__ import annotations
from pathlib import Path

import numpy as np
from fastcore.all import AttrDict, L, store_attr

from .core import Model, infer_task, model_file, prep_from_spec, sidecar_labels, with_hub_defaults
from .vision import read_labels

# %% auto #0
__all__ = ['PROVIDER_ORDER', 'best_providers', 'mk_session', 'OnnxModel']

# %% ../nbs/02_onnx.ipynb #9cdbb990
_ORT_DTYPES = {'tensor(float)': 'float32', 'tensor(float16)': 'float16', 'tensor(double)': 'float64',
               'tensor(uint8)': 'uint8', 'tensor(int8)': 'int8', 'tensor(int32)': 'int32',
               'tensor(int64)': 'int64', 'tensor(bool)': 'bool'}

PROVIDER_ORDER = ('TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CoreMLExecutionProvider',
                  'ROCMExecutionProvider', 'CPUExecutionProvider')

def best_providers() -> list:
    'The available execution providers, fastest first.'
    import onnxruntime as ort
    have = set(ort.get_available_providers())
    return [p for p in PROVIDER_ORDER if p in have] or ['CPUExecutionProvider']

def mk_session(path, providers=None, intra_threads:int=None, log:int=3):
    'An `onnxruntime.InferenceSession` over `path`, quiet by default.'
    import onnxruntime as ort
    so = ort.SessionOptions()
    so.log_severity_level = log
    if intra_threads: so.intra_op_num_threads = intra_threads
    return ort.InferenceSession(str(path), sess_options=so, providers=providers or best_providers())

# %% ../nbs/02_onnx.ipynb #5ce83ca0
class OnnxModel(Model):
    'An ONNX graph as a `Model`: shapes and dtypes come from the session, labels and norm from the caller or the hub.'
    _runtime = 'onnx'

    def __init__(self,
                 model=None,             # a path to an .onnx file, or a hub repo id
                 *,
                 runtime:str=None,       # ignored; `Model` has already dispatched on it
                 model_path=None,        # an explicit file, skipping resolution
                 file:str=None,          # which file to take from a repo that ships several
                 revision:str=None,
                 task:str=None,          # override the task guessed from the output shapes
                 labels=None,            # class names: a list, a labels.txt, or a config.json
                 norm=None,              # a NORMS name or an explicit (mean, std); the repo's config by default
                 size:tuple=None,        # the input size, for a graph with symbolic spatial axes
                 resize:str=None,        # 'stretch', 'letterbox', 'center_crop'
                 prep=None,              # a fully built Prep, overriding everything above
                 topk:int=5, conf:float=0.25, iou:float=0.45,
                 providers=None,         # execution providers, fastest-available by default
                 sess=None,              # an already-built session to reuse
                 max_bs:int=16,          # cap on batching, when the graph allows any
                 **kw):
        model = self._setup(model, task=task, labels=labels, topk=topk, conf=conf, iou=iou)
        self.model_path = str(model_file(model, model_path, file=file, revision=revision))
        self._sess = sess or mk_session(self.model_path, providers=providers, **kw)
        self._read_spec()
        labels, pk = with_hub_defaults(self.model_path, self.labels, norm=norm, size=size, resize=resize)
        self.labels = read_labels(labels) or read_labels(sidecar_labels(self.model_path))
        self._task = task or infer_task([o.shape for o in self.outputs], self.labels,
                                        [o.name for o in self.outputs])
        self._prep = prep or prep_from_spec(self.inp.shape, self.inp.dtype, task=self._task, **pk)
        self._max_bs = self._batch_limit(max_bs)

    def _read_spec(self):
        'Input and output signatures, with ONNX Runtime type strings turned into numpy dtypes.'
        f = lambda o: AttrDict(name=o.name, shape=list(o.shape), dtype=_ORT_DTYPES.get(o.type, 'float32'))
        self.inputs, self.outputs = L(self._sess.get_inputs()).map(f), L(self._sess.get_outputs()).map(f)
        if len(self.inputs) > 1: raise ValueError(
            f'{Path(self.model_path).name} takes {len(self.inputs)} inputs '
            f'({", ".join(self.inputs.attrgot("name"))}); anya drives single-input vision graphs.')
        self.inp = self.inputs[0]

    def _batch_limit(self, mx:int) -> int:
        "A fixed batch axis is the limit; a symbolic one means `mx` is."
        b = self.inp.shape[0]
        return b if isinstance(b, int) and b > 0 else mx

    @property
    def spec(self) -> AttrDict:
        'What the graph declares, as plain dicts.'
        return AttrDict(inputs=list(self.inputs), outputs=list(self.outputs), providers=self._sess.get_providers())

    def _infer(self, x) -> list:
        if self._sess is None: raise RuntimeError('this model is closed')
        return self._sess.run(None, {self.inp.name: x.astype(self.inp.dtype, copy=False)})
