"""Doubles, so code that uses anya can be tested with no runtime and no weights.

Docs: https://vedicreader.github.io/anya/testing.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_testing.ipynb.

# %% ../nbs/08_testing.ipynb #a2a543dd
from __future__ import annotations

import numpy as np
from fastcore.all import L

from .core import Model, Pred, Preds, item_src, items
from .vision import Prep

# %% auto #0
__all__ = ['FakeModel', 'fake_segment', 'fake_detect']

# %% ../nbs/08_testing.ipynb #383e3f77
class FakeModel(Model):
    'A model that answers from a script, for testing a pipeline with no runtime installed.'
    _runtime = 'fake'

    def __init__(self,
                 answer=None,          # a dict of payload keys, or `f(item) -> dict`
                 task:str='classify',
                 labels=None,
                 name:str='fake',
                 **kw):
        self._setup(name, task=task, labels=labels, **kw)
        self._prep = Prep(size=None)
        self.answer = answer or {}

    def _read_spec(self): pass
    def _infer(self, x): raise NotImplementedError('a fake model has no graph to run')

    def predict(self, o, **kw) -> Pred:
        'The scripted answer, with this item named as its source.'
        a = self.answer(o) if callable(self.answer) else dict(self.answer)
        return Pred(dict(src=item_src(o), task=self.task, model=self.name), **a)

    def predict_all(self, o, bs:int=None, on_error:str='skip', types:str=None, exclude=None, **kw) -> Preds:
        'The same answer for every item the folder holds.'
        return Preds([self.predict(x, **kw) for x in items(o, types=types or self.modality, exclude=exclude)])

def fake_segment(blocks:dict,           # {'label': (x1, y1, x2, y2)}, painted in the order given
                 size:tuple=(64, 64),   # (width, height) of the label map
                 bg:str='background'    # the label for class 0
                ) -> FakeModel:
    'A segmenter whose label map is the rectangles you name. Class 0 is whatever is left.'
    labels = [bg] + list(blocks)
    m = np.zeros((size[1], size[0]), np.int32)
    for i, (k, b) in enumerate(blocks.items(), 1): m[b[1]:b[3], b[0]:b[2]] = i
    ids, cnt = np.unique(m, return_counts=True)
    cls = [dict(label=labels[int(i)], index=int(i), frac=round(float(c/m.size), 5))
           for i, c in sorted(zip(ids, cnt), key=lambda t: -t[1])]
    return FakeModel(dict(mask=m, shape=list(m.shape), classes=cls), task='segment', labels=labels)

def fake_detect(objects:list,           # [{'label', 'score', 'box'}], the boxes a detector would return
                labels=None) -> FakeModel:
    'A detector that returns the boxes you give it.'
    return FakeModel(dict(objects=list(objects)), task='detect',
                     labels=labels or sorted({o['label'] for o in objects}))
