"""The same jobs, shaped for a model to call: strings in, small JSON out, nothing destructive by default.

Docs: https://vedicreader.github.io/anya/tools.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_tools.ipynb.

# %% ../nbs/07_tools.ipynb #bdadac5a
from __future__ import annotations
import inspect, json, sys
from pathlib import Path

import numpy as np
from fastcore.all import AttrDict, L

from .core import Preds, arrange, items, load_model
from .tasks import as_model, bench, classify, detect, find_similar, segment, sort_images, summarize

# %% auto #0
__all__ = ['SAFE', 'WRITE', 'TOOLS', 'find_model', 'model_info', 'name_model', 'classify_image', 'detect_image', 'segment_image',
           'classify_folder', 'sort_folder', 'similar_images', 'label_video', 'count_images', 'tool_names', 'main']

# %% ../nbs/07_tools.ipynb #11a367f4
def find_model(query:str,           # what the model should do, in words
               task:str=None,       # 'classify', 'detect', 'segment', 'embed'
               runtime:str=None,    # 'litert' for on-device, 'onnx', 'coreml'
               n:int=5              # how many candidates
              ) -> dict:
    'Search the model hub for a model anya can run, most downloaded first.'
    from anya.hub import find_models, web_models
    try: ms = find_models(query, task=task, runtime=runtime, n=n)
    except Exception as e:
        try: ms = web_models(query, n=n)
        except Exception: return dict(query=query, error=f'{type(e).__name__}: {e}', models=[])
    return dict(query=query, task=task, runtime=runtime, models=[dict(m) for m in ms])

def model_info(model:str,           # a path, hub repo id, or alias
               task:str=None,       # force the task, when the output shapes are ambiguous
               labels:str=None      # a labels file, when the model does not carry its own
              ) -> dict:
    'Load a model and report what it does: task, runtime, input size, and how many classes.'
    m = as_model(model, **{k: v for k, v in dict(task=task, labels=labels).items() if v})
    return dict(model=m.name, runtime=m.runtime, task=m.task, prep=repr(m.prep),
                n_labels=len(m.labels) if m.labels else 0,
                labels=list(m.labels[:20]) if m.labels else [],
                inputs=[dict(i) for i in m.inputs], outputs=[dict(o) for o in m.outputs],
                max_batch=m.max_bs)

def name_model(alias:str,           # the short name to use from now on
               repo:str,            # the hub repo id or local path it stands for
               file:str=None,       # which file inside the repo, when it ships several
               labels:str=None      # a labels file, when the model does not carry its own
              ) -> dict:
    'Save a short name for a model, so later calls can use it instead of the repo id.'
    from anya.hub import alias as _alias
    kw = {k: v for k, v in dict(file=file, labels=labels).items() if v}
    return dict(alias=alias, saved=_alias(alias, repo, **kw).get(alias))

# %% ../nbs/07_tools.ipynb #b2ed0885
def classify_image(path:str,        # the picture to look at
                   model:str,       # a path, hub repo id, or alias
                   topk:int=3       # how many labels to return
                  ) -> dict:
    'What is in this picture, as ranked labels.'
    p = classify(path, model, topk=topk)
    return dict(src=str(path), model=p.get('model'), labels=p.get('preds', []), error=p.get('error'))

def detect_image(path:str,          # the picture to look at
                 model:str,         # a detector
                 conf:float=0.25,   # ignore anything less confident
                 limit:int=50       # cap the objects returned
                ) -> dict:
    'What objects are in this picture and where, as xyxy boxes in the original pixels.'
    p = detect(path, model, conf=conf)
    o = p.get('objects', [])
    return dict(src=str(path), model=p.get('model'), n=len(o), objects=o[:limit], error=p.get('error'))

def segment_image(path:str,         # the picture to look at
                  model:str         # a segmentation model
                 ) -> dict:
    'Which classes cover this picture, and what share of the pixels each one covers.'
    p = segment(path, model)
    return dict(src=str(path), model=p.get('model'), classes=p.get('classes', []),
                shape=p.get('shape'), error=p.get('error'))

# %% ../nbs/07_tools.ipynb #d2172bdb
def classify_folder(folder:str,             # folder of pictures
                    model:str,              # a classifier
                    min_score:float=0.0,    # ignore predictions below this
                    limit:int=25,           # how many individual items to include
                    save:str=None           # write every result to this JSON file
                   ) -> dict:
    'Classify every picture in a folder and report the tally.'
    ps = classify(folder, model, topk=1)
    keep = ps.above(min_score) if min_score else ps.ok
    out = dict(folder=str(folder), model=(ps[0].get('model') if len(ps) else None),
               **summarize(ps), kept=len(keep),
               items=[dict(src=p['src'], label=p.label, score=p.score) for p in keep[:limit]])
    if save: out['saved'] = str(ps.save(save))
    return out

def sort_folder(folder:str,                 # folder of pictures to sort
                model:str,                  # a classifier
                dest:str=None,              # where the sorted tree goes; default is <folder>/sorted
                min_score:float=0.5,        # anything less confident goes to unsorted/
                how:str='copy',             # 'copy', 'move', or 'link'
                apply:bool=False,           # False returns the plan and moves nothing
                limit:int=25                # how many planned moves to show
               ) -> dict:
    'Sort a folder of pictures into folders named after what the model saw. Plans unless `apply=True`.'
    r = sort_images(folder, model, dest=dest, min_score=min_score, how=how, dry_run=not apply)
    return dict(folder=str(folder), dest=r['dest'], how=how, applied=bool(apply), n=r['n'],
                moved=r['moved'], labels=r['labels'], counts=r['counts'], failed=r['failed'],
                plan=r['plan'][:limit])

def similar_images(query:str,               # the picture to match
                   folder:str,              # where to look
                   model:str,               # an embedding model
                   n:int=10                 # how many to return
                  ) -> dict:
    'Rank the pictures in a folder by how much they look like one picture.'
    hits = find_similar(query, folder, model, n=n)
    return dict(query=str(query), folder=str(folder), n=len(hits), hits=[dict(h) for h in hits])

def label_video(path:str,                   # the video to look at
                model:str,                  # a classifier or detector
                every:float=1.0,            # seconds between sampled frames
                max_frames:int=20           # stop after this many frames
               ) -> dict:
    'Sample frames from a video and label each one, with its timestamp.'
    m = as_model(model)
    ps = m.predict_video(path, every=every, max_frames=max_frames)
    return dict(src=str(path), model=m.name, task=m.task, n=len(ps), counts=ps.counts(),
                frames=[dict(t=p.get('t'), label=p.label, score=p.score) for p in ps])

def count_images(folder:str,                # folder to look in
                 types:str='image'          # 'image', 'audio', 'video', or 'any'
                ) -> dict:
    'How many files anya would run on in this folder, before running anything.'
    xs = items(folder, types=types)
    return dict(folder=str(folder), n=len(xs), sample=[str(x) for x in xs[:10]])

# %% ../nbs/07_tools.ipynb #75f6b158
SAFE = [find_model, model_info, count_images, classify_image, detect_image, segment_image,
        classify_folder, similar_images, label_video]
WRITE = [sort_folder, name_model]
TOOLS = SAFE + WRITE

def tool_names() -> list:
    'The names a chat will see.'
    return [f.__name__ for f in TOOLS]

# %% ../nbs/07_tools.ipynb #57ff7733
def _coerce(v:str, ann):
    'Command line strings into the types a tool declares.'
    # `from __future__ import annotations` hands every annotation over as a string, so match the name
    t = getattr(ann, '__name__', str(ann))
    if t == 'bool': return str(v).lower() not in ('0', 'false', 'no', '')
    if t == 'int': return int(v)
    if t == 'float': return float(v)
    return v

def main(argv=None) -> int:
    'Entry point for the `anya` command: `anya <tool> [positional…] [--flag=value…]`.'
    argv = list(sys.argv[1:] if argv is None else argv)
    by_name = {f.__name__: f for f in TOOLS}
    if not argv or argv[0] in ('-h', '--help', 'help'):
        print('anya <tool> [args] [--flag=value]\n\ntools:')
        for f in TOOLS: print(f'  {f.__name__:16s} {(f.__doc__ or "").splitlines()[0]}')
        return 0
    name, rest = argv[0], argv[1:]
    if name not in by_name:
        print(f'unknown tool {name!r}; one of: {", ".join(by_name)}', file=sys.stderr); return 2
    f = by_name[name]
    ps = list(inspect.signature(f).parameters.values())
    pos = [a for a in rest if not a.startswith('--')]
    kw = dict(a[2:].split('=', 1) for a in rest if a.startswith('--') and '=' in a)
    kw |= {a[2:]: 'true' for a in rest if a.startswith('--') and '=' not in a}
    args = {p.name: _coerce(v, p.annotation) for p, v in zip(ps, pos)}
    args |= {k: _coerce(v, next((p.annotation for p in ps if p.name == k), str)) for k, v in kw.items()}
    print(json.dumps(f(**args), indent=1, default=str))
    return 0
